version: '3.8'

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    labels:
      io.containers.autoupdate: registry
    network_mode: host
    pid: host
    restart: always
    volumes:
      - '/:/host:ro,rslave'
