- name: Bring down arcane-agent
  hosts:
    - servers
    - workstations

  tasks:
    - name: Bring down service
      ansible.builtin.import_tasks: ../common/tasks.down.yaml
      vars:
        fw_services:
          to_disable:
            - arcane-agent
        systemd_services:
          - arcane-agent.service
