- name: Create the Quadlet directory
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/containers/systemd"
    state: directory
    mode: "0755"

- name: Copy the Quadlet files
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/systemd/"
    dest: "{{ lookup('env', 'HOME') }}/.config/containers/systemd"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: "0644"
  register: result

- name: Populate service facts
  ansible.builtin.service_facts:

- name: Configure Firewall
  become: true
  when:
    - services['firewalld.service'] is defined
    - services['firewalld.service']['state'] == 'running'
  block:
    - name: Add Firewall Services
      ansible.builtin.shell: |
        firewall-cmd --permanent --new-service={{ item.name }}
        firewall-cmd --permanent --service={{ item.name }} --add-port={{ item.port }}
      args:
        creates: "/etc/firewalld/services/{{ item.name }}.xml"
      with_items: "{{ fw_services.to_create | default([]) }}"
      register: addservices
    - name: Reload Firewall
      ansible.builtin.command: firewall-cmd --reload
      when: addservices.changed
    - name: Enable Firewall Services
      ansible.posix.firewalld:
        service: "{{ item }}"
        immediate: true
        permanent: true
        state: enabled
      with_items: "{{ fw_services.to_enable | default([]) }}"

- name: Start the systemd services
  ansible.builtin.systemd:
    name: "{{ item }}"
    daemon_reload: true
    scope: user
    state: restarted
  with_items: "{{ systemd_services | default([]) }}"
  when: result is changed
