- name: Bring down portainer-agent
  hosts:
    - servers
    - workstations

  tasks:
    - name: Bring down service
      ansible.builtin.import_tasks: ../common/tasks.down.yaml
      vars:
        fw_services:
          to_disable:
            - portainer-agent
        systemd_services:
          - portainer-agent.service
