- name: Bring down prometheus-podman-exporter
  hosts:
    - servers
    - workstations

  tasks:
    - name: Bring down service
      ansible.builtin.import_tasks: ../common/tasks.down.yaml
      vars:
        fw_services:
          to_disable:
            - prometheus-podman-exporter
        systemd_services:
          - prometheus-podman-exporter.service
