- name: Bring up node-exporter
  hosts:
    - servers
    - workstations

  tasks:
    - name: Bring up service
      ansible.builtin.import_tasks: ../common/tasks.up.yaml
      vars:
        fw_services:
          to_create:
            - name: node-exporter
              port: 9100/tcp
          to_enable:
            - node-exporter
        systemd_services:
          - node_exporter.service
